[package]
name = "flux-store"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
flux-core = { path = "../flux-core" }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "migrate"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
