//! Permanent regression guard for the LLM-facing tool schemas.
//!
//! Schemas are generated by the `#[derive(Tool)]` macro from struct fields
//! (doc comments as descriptions, `Option<T>` optional, `#[tool(skip)]`
//! excluded). This test pins their semantic shape — property names, JSON
//! types, descriptions, required lists, and `additionalProperties: false` —
//! so changes to the derive macro or the tool structs fail loudly instead of
//! silently altering the contract exposed to the LLM.
//!
//! Tools are pure executors over authoritative context: the chat boundary
//! (`workdir` / `current_dir`) rides `ToolCtx` and never appears in a tool
//! schema — there is nothing for the LLM to (dis)agree about.

use flux_core::Tool;
use flux_tools::{
    BashTool, EditFileTool, EditFilesTool, GlobTool, GrepTool, ListDirectoryTool, ReadFileTool,
    ReadFilesTool, ReplaceLinesTool, SkillListTool, WriteFileTool,
};

fn expected_schema(name: &str) -> serde_json::Value {
    match name {
        "read_file" => serde_json::json!({
            "type": "object",
            "properties": {
                "file_path": { "type": "string", "description": "Path to the file to read." },
                "offset": { "type": "integer", "description": "Line number to start reading from (1-based)." },
                "limit": { "type": "integer", "description": "Maximum number of lines to read." },
            },
            "required": ["file_path"],
            "additionalProperties": false,
        }),
        "read_files" => serde_json::json!({
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "file_path": { "type": "string", "description": "Path to the file to read." },
                            "offset": { "type": "integer", "description": "Line number to start reading from (1-based)." },
                            "limit": { "type": "integer", "description": "Maximum number of lines to read." },
                        },
                        "required": ["file_path"],
                        "additionalProperties": false,
                    },
                    "description": "Files to read, one segment each (1..=16 items).",
                },
            },
            "required": ["files"],
            "additionalProperties": false,
        }),
        "edit_file" => serde_json::json!({
            "type": "object",
            "properties": {
                "file_path": { "type": "string", "description": "Path to the file to edit." },
                "old_string": { "type": "string", "description": "Exact text to replace, copied verbatim from a recent read_file (no line-number prefixes). Must be unique in the file unless replace_all is true." },
                "new_string": { "type": "string", "description": "Replacement text. An empty string deletes the matched text." },
                "replace_all": { "type": "boolean", "description": "Replace every occurrence of old_string instead of requiring a unique match." },
            },
            "required": ["file_path", "old_string", "new_string"],
            "additionalProperties": false,
        }),
        "edit_files" => serde_json::json!({
            "type": "object",
            "properties": {
                "edits": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "file_path": { "type": "string", "description": "Path to the file to edit." },
                            "old_string": { "type": "string", "description": "Exact text to replace, copied verbatim from a recent read_file (no line-number prefixes). Must be unique in the file unless replace_all is true." },
                            "new_string": { "type": "string", "description": "Replacement text. An empty string deletes the matched text." },
                            "replace_all": { "type": "boolean", "description": "Replace every occurrence of old_string instead of requiring a unique match." },
                        },
                        "required": ["file_path", "old_string", "new_string"],
                        "additionalProperties": false,
                    },
                    "description": "Edits to apply, grouped by file automatically (1..=16 items); same-file edits run in listed order and report per edit.",
                },
            },
            "required": ["edits"],
            "additionalProperties": false,
        }),
        "write_file" => serde_json::json!({
            "type": "object",
            "properties": {
                "file_path": { "type": "string", "description": "Path to the file to write." },
                "content": { "type": "string", "description": "The full new content to write to the file." },
            },
            "required": ["file_path", "content"],
            "additionalProperties": false,
        }),
        "replace_lines" => serde_json::json!({
            "type": "object",
            "properties": {
                "file_path": { "type": "string", "description": "Path to the file to edit." },
                "start_line": { "type": "integer", "description": "First line of the range (1-based, inclusive)." },
                "end_line": { "type": "integer", "description": "Last line of the range (1-based, inclusive). start_line = end_line + 1 inserts before start_line without removing lines." },
                "content": { "type": "string", "description": "Replacement content for the range. Empty deletes the range." },
            },
            "required": ["file_path", "start_line", "end_line", "content"],
            "additionalProperties": false,
        }),
        "list_directory" => serde_json::json!({
            "type": "object",
            "properties": {
                "path": { "type": "string", "description": "Path to the directory to list. Defaults to current directory." },
            },
            "required": [],
            "additionalProperties": false,
        }),
        "grep" => serde_json::json!({
            "type": "object",
            "properties": {
                "pattern": { "type": "string", "description": "Regex pattern to search for." },
                "path": { "type": "string", "description": "Directory or file to search in. Defaults to the chat workdir." },
            },
            "required": ["pattern"],
            "additionalProperties": false,
        }),
        "glob" => serde_json::json!({
            "type": "object",
            "properties": {
                "pattern": { "type": "string", "description": "Glob pattern to match files against (relative to the chat's current working directory)." },
            },
            "required": ["pattern"],
            "additionalProperties": false,
        }),
        "bash" => serde_json::json!({
            "type": "object",
            "properties": {
                "command": { "type": "string", "description": "The shell command to execute." },
                "timeout": { "type": "integer", "description": "Timeout in seconds (default 300, clamped to 1..=1800)." },
            },
            "required": ["command"],
            "additionalProperties": false,
        }),
        "skill_list" => serde_json::json!({
            "type": "object",
            "properties": {},
            "required": [],
            "additionalProperties": false,
        }),
        other => panic!("unexpected tool name: {other}"),
    }
}

#[test]
fn all_tool_schemas_match_the_pinned_contract() {
    let tools: Vec<(&str, Box<dyn Tool>)> = vec![
        ("read_file", Box::new(ReadFileTool::new())),
        ("read_files", Box::new(ReadFilesTool::new())),
        ("edit_file", Box::new(EditFileTool::new())),
        ("edit_files", Box::new(EditFilesTool::new())),
        ("write_file", Box::new(WriteFileTool::new())),
        ("replace_lines", Box::new(ReplaceLinesTool::new())),
        ("list_directory", Box::new(ListDirectoryTool::new())),
        ("grep", Box::new(GrepTool::new())),
        ("glob", Box::new(GlobTool::new())),
        ("bash", Box::new(BashTool::new())),
        ("skill_list", Box::new(SkillListTool::new())),
    ];

    for (name, tool) in &tools {
        assert_eq!(
            &expected_schema(name),
            &tool.schema(),
            "generated schema drifted from the pinned contract for {name}"
        );
        // The boundary is invocation context, not LLM surface: no tool
        // schema carries `workdir` or `current_dir`.
        for boundary_key in ["workdir", "current_dir"] {
            assert!(
                tool.schema()["properties"].get(boundary_key).is_none(),
                "{boundary_key} must not be schema-visible for {name}"
            );
        }
    }
}
